# - name: Add docker apt keys
#   apt_key: 
#     keyserver: keyserver.ubuntu.com 
#     id: 36A1D7869245C8950F966E92D8576A8BA88D21E9
#   tags: [docker]
- name: Ensure APT transport HTTPS is installed | Debian / Ubuntu
  apt:
    name: 'apt-transport-https'
    state: installed
  tags: [docker]

- name: Add docker apt keys
  apt_key: 
    keyserver: p80.pool.sks-keyservers.net 
    id: 58118E89F3A912897C070ADBF76221572C52609D
  tags: [docker]

# - name: Update apt
#   apt_repository: repo='deb https://get.docker.com docker main' state=present

- name: Debian add Docker repository and update apt cache
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
    update_cache: yes
    state: present
  tags: [docker]

- name: Debian Docker is present
  apt:
    name: docker-engine
    state: latest
    force: yes
  tags: [docker]

  
# - name: Install Docker
#   apt: pkg=lxc-docker update_cache=yes
#   tags: [docker]

- name: Debian python-pip is present
  apt: name=python-pip state=present
  tags: [docker]

- name: Debian docker-py is present
  pip: name=docker-py version=0.4.0 state=present
  tags: [docker]

- name: Debian files are present
  template:
    src: "{{ docker_cfg }}"
    dest: /lib/systemd/system/docker.service
  register: copy_result
  tags: [docker]

- name: Debian Daemon is reloaded
  shell: systemctl daemon-reload
  when: copy_result|changed
  tags: [docker]

- name: vagrant user is added to the docker group
  user:
    name: vagrant
    group: docker
  register: user_result
  tags: [docker]

- name: Debian Docker service is restarted
  service:
    name: docker
    state: restarted
  when: copy_result|changed or user_result|changed
  tags: [docker]
